### PR TITLE
rename to just rpm

### PR DESCRIPTION
**Pull request by drahnr**
Follow up to #4 

I propose to craft a release as `0.0.1` under the new name `rpm` with the current state and iterate quickly and bump to `0.1.0` once a decent level of documentation exists.

Once merged, I'd also rename the name of this repo accordingly to `rpm`

### CODE REVIEW

**Review by dralley — APPROVED** [review]

**Comment by drahnr** [comment]
Renamed repository to `rpm` :tada: - we should discuss when to slate the `0.0.1` release

**Comment by dralley** [comment]
> I propose to craft a release as 0.0.1 under the new name rpm with the current state and iterate quickly and bump to 0.1.0 once a decent level of documentation exists.

That's fine with me, I'm slightly partial to picking up where the other crate left off in terms of versioning, but I don't feel strongly about it at all

**Comment by drahnr** [comment]
We could do either, no strong opinion either.

**Comment by dralley** [comment]
I don't think we need to overthink the "when" too much, the signing fix alone is justification for a release.

We need to update the changelog though - probably we should have been doing that in the PRs, but it slipped my mind.

**Pull request merged**
